server.port=${PORT:8080}

bfhl.user.full-name=your_full_name
bfhl.user.dob=DDMMYYYY
bfhl.user.email=YOUR_EMAIL
bfhl.user.roll-number=YOUR_ROLL_NUMBER

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha